import React from 'react'

import { Helmet } from 'react-helmet'

import './loginscreen1.css'

const Loginscreen1 = (props) => {
  return (
    <div className="loginscreen1-container">
      <Helmet>
        <title>exported project</title>
      </Helmet>
      <div className="loginscreen1-loginscreen">
        <div className="loginscreen1-status-bari-phone13">
          <div className="loginscreen1-left-side">
            <div className="loginscreen1-frame-status-bartime">
              <span className="loginscreen1-text10 DefaultBoldBody">
                <span>9:41</span>
              </span>
            </div>
          </div>
          <div className="loginscreen1-right-side">
            <div className="loginscreen1-battery">
              <img
                alt="OutlineI391"
                src="/external/outlinei391-p7s.svg"
                className="loginscreen1-outline"
              />
              <img
                alt="BatteryEndI391"
                src="/external/batteryendi391-c0o.svg"
                className="loginscreen1-battery-end"
              />
              <img
                alt="FillI391"
                src="/external/filli391-1d8s.svg"
                className="loginscreen1-fill"
              />
            </div>
            <img
              alt="WifiI391"
              src="/external/wifii391-wzio.svg"
              className="loginscreen1-wifi"
            />
            <img
              alt="IconMobileSignalI391"
              src="/external/iconmobilesignali391-6inh.svg"
              className="loginscreen1-icon-mobile-signal"
            />
          </div>
        </div>
        <img
          alt="Rectangle243911"
          src="/external/rectangle243911-1dxb-200h.png"
          className="loginscreen1-rectangle24"
        />
        <div className="loginscreen1-byerafiki">
          <div className="loginscreen1-backgroundcomplete">
            <img
              alt="Vector3911"
              src="/external/vector3911-5ipm.svg"
              className="loginscreen1-vector10"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-uvcc.svg"
              className="loginscreen1-vector11"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-qqhb.svg"
              className="loginscreen1-vector12"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-pnp.svg"
              className="loginscreen1-vector13"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-fs5f.svg"
              className="loginscreen1-vector14"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-xg1n.svg"
              className="loginscreen1-vector15"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-yrpi.svg"
              className="loginscreen1-vector16"
            />
          </div>
          <div className="loginscreen1-shadow">
            <img
              alt="path3911"
              src="/external/path3911-fbfm.svg"
              className="loginscreen1-path"
            />
          </div>
          <div className="loginscreen1-character1">
            <img
              alt="Vector3911"
              src="/external/vector3911-r5a.svg"
              className="loginscreen1-vector17"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-bsxm.svg"
              className="loginscreen1-vector18"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-x49.svg"
              className="loginscreen1-vector19"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-7shr.svg"
              className="loginscreen1-vector20"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-1qv.svg"
              className="loginscreen1-vector21"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-gy2q.svg"
              className="loginscreen1-vector22"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-xrl.svg"
              className="loginscreen1-vector23"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-6u.svg"
              className="loginscreen1-vector24"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-1sz6.svg"
              className="loginscreen1-vector25"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-qjzh.svg"
              className="loginscreen1-vector26"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-cc2p.svg"
              className="loginscreen1-vector27"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-7xct.svg"
              className="loginscreen1-vector28"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-e42i.svg"
              className="loginscreen1-vector29"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-tciq.svg"
              className="loginscreen1-vector30"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-rwfw.svg"
              className="loginscreen1-vector31"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-2w8.svg"
              className="loginscreen1-vector32"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-l0pd.svg"
              className="loginscreen1-vector33"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-u1e3.svg"
              className="loginscreen1-vector34"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-umdk.svg"
              className="loginscreen1-vector35"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-38nl.svg"
              className="loginscreen1-vector36"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-ptw.svg"
              className="loginscreen1-vector37"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-ni0h.svg"
              className="loginscreen1-vector38"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-umf8.svg"
              className="loginscreen1-vector39"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-2a4l.svg"
              className="loginscreen1-vector40"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-nem.svg"
              className="loginscreen1-vector41"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-lo2a.svg"
              className="loginscreen1-vector42"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-32o5.svg"
              className="loginscreen1-vector43"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-zlz6.svg"
              className="loginscreen1-vector44"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-tsma.svg"
              className="loginscreen1-vector45"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-zfy.svg"
              className="loginscreen1-vector46"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-x4y8.svg"
              className="loginscreen1-vector47"
            />
          </div>
          <div className="loginscreen1-character2">
            <img
              alt="Vector3911"
              src="/external/vector3911-pxyg.svg"
              className="loginscreen1-vector48"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-bmkh.svg"
              className="loginscreen1-vector49"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-c0i5.svg"
              className="loginscreen1-vector50"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-upag.svg"
              className="loginscreen1-vector51"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-k1ai.svg"
              className="loginscreen1-vector52"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-ddm4.svg"
              className="loginscreen1-vector53"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-lgei.svg"
              className="loginscreen1-vector54"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-ivo.svg"
              className="loginscreen1-vector55"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-di58.svg"
              className="loginscreen1-vector56"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-7mon.svg"
              className="loginscreen1-vector57"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-upty.svg"
              className="loginscreen1-vector58"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-wx4o.svg"
              className="loginscreen1-vector59"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-tqg.svg"
              className="loginscreen1-vector60"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-hugh.svg"
              className="loginscreen1-vector61"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-78aq.svg"
              className="loginscreen1-vector62"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-ydg.svg"
              className="loginscreen1-vector63"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-qprr.svg"
              className="loginscreen1-vector64"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-tvs.svg"
              className="loginscreen1-vector65"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-p68.svg"
              className="loginscreen1-vector66"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-08ff.svg"
              className="loginscreen1-vector67"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-rrmj.svg"
              className="loginscreen1-vector68"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-jipj.svg"
              className="loginscreen1-vector69"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-tqys.svg"
              className="loginscreen1-vector70"
            />
            <img
              alt="Vector3911"
              src="/external/vector3911-63ds.svg"
              className="loginscreen1-vector71"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-qljj.svg"
              className="loginscreen1-vector72"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-gkos.svg"
              className="loginscreen1-vector73"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-ymr.svg"
              className="loginscreen1-vector74"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-ocl.svg"
              className="loginscreen1-vector75"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-gwmk.svg"
              className="loginscreen1-vector76"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-fpm.svg"
              className="loginscreen1-vector77"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-8ima.svg"
              className="loginscreen1-vector78"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-k4pw.svg"
              className="loginscreen1-vector79"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-soh.svg"
              className="loginscreen1-vector80"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-gb144.svg"
              className="loginscreen1-vector81"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-qlli.svg"
              className="loginscreen1-vector82"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-tm9.svg"
              className="loginscreen1-vector83"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-55sh.svg"
              className="loginscreen1-vector84"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-2zqt.svg"
              className="loginscreen1-vector85"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-ixui.svg"
              className="loginscreen1-vector86"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-mj0l.svg"
              className="loginscreen1-vector87"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-eh7n.svg"
              className="loginscreen1-vector88"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-3ja.svg"
              className="loginscreen1-vector89"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-lfm.svg"
              className="loginscreen1-vector90"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-fnfg.svg"
              className="loginscreen1-vector91"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-eq2p.svg"
              className="loginscreen1-vector92"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-wr7w.svg"
              className="loginscreen1-vector93"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-nw49.svg"
              className="loginscreen1-vector94"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-dvoi.svg"
              className="loginscreen1-vector95"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-su4j.svg"
              className="loginscreen1-vector96"
            />
          </div>
        </div>
        <div className="loginscreen1-icon1">
          <span className="loginscreen1-text12"></span>
        </div>
        <div className="loginscreen1-frame16">
          <div className="loginscreen1-text-styles1">
            <span className="loginscreen1-text13 Heading">
              <span>Login</span>
            </span>
          </div>
          <div className="loginscreen1-frame15">
            <div className="loginscreen1-frame12">
              <div className="loginscreen1-icon2">
                <span className="loginscreen1-text15 SingleLineBodyBase">
                  @
                </span>
              </div>
              <div className="loginscreen1-text-styles2">
                <span className="loginscreen1-text16 SingleLineBodyBase">
                  <span>redwoodgreens@gmail.com</span>
                </span>
              </div>
            </div>
            <div className="loginscreen1-frame14">
              <div className="loginscreen1-icon3">
                <span className="loginscreen1-text18"></span>
              </div>
              <div className="loginscreen1-text-styles3">
                <span className="loginscreen1-text19 SingleLineBodyBase">
                  <span>..........</span>
                </span>
              </div>
            </div>
            <div className="loginscreen1-text-styles4">
              <span className="loginscreen1-text21 BodySmall">
                <span> Forgot Password?</span>
              </span>
            </div>
          </div>
        </div>
        <div className="loginscreen1-frame18">
          <button className="loginscreen1-buttons1">
            <span className="loginscreen1-text23 Body-14pxMedium">
              <span>Continue</span>
            </span>
          </button>
          <div className="loginscreen1-frame17">
            <img
              alt="Line133912"
              src="/external/line133912-yc2a.svg"
              className="loginscreen1-line13"
            />
            <div className="loginscreen1-text-styles5">
              <span className="loginscreen1-text25">
                <span>OR</span>
              </span>
            </div>
            <img
              alt="Line143912"
              src="/external/line143912-1tzq.svg"
              className="loginscreen1-line14"
            />
          </div>
          <button className="loginscreen1-buttons2">
            <img
              alt="svg013912"
              src="/external/svg013912-1amm.svg"
              className="loginscreen1-svg01"
            />
            <span className="loginscreen1-text27 Body-14pxMedium">
              <span>Login with Google</span>
            </span>
          </button>
        </div>
      </div>
    </div>
  )
}

export default Loginscreen1
