import React from 'react'

import { Helmet } from 'react-helmet'

import './loginscreen.css'

const Loginscreen = (props) => {
  return (
    <div className="loginscreen-container">
      <Helmet>
        <title>exported project</title>
      </Helmet>
      <div className="loginscreen-loginscreen">
        <div className="loginscreen-status-bari-phone13">
          <div className="loginscreen-left-side">
            <div className="loginscreen-frame-status-bartime">
              <span className="loginscreen-text1 DefaultBoldBody">
                <span>9:41</span>
              </span>
            </div>
          </div>
          <div className="loginscreen-right-side">
            <div className="loginscreen-battery">
              <img
                alt="OutlineI391"
                src="/external/outlinei391-zs1f.svg"
                className="loginscreen-outline"
              />
              <img
                alt="BatteryEndI391"
                src="/external/batteryendi391-tdek.svg"
                className="loginscreen-battery-end"
              />
              <img
                alt="FillI391"
                src="/external/filli391-g1w.svg"
                className="loginscreen-fill"
              />
            </div>
            <img
              alt="WifiI391"
              src="/external/wifii391-y6we.svg"
              className="loginscreen-wifi"
            />
            <img
              alt="IconMobileSignalI391"
              src="/external/iconmobilesignali391-gez.svg"
              className="loginscreen-icon-mobile-signal"
            />
          </div>
        </div>
        <img
          alt="Rectangle243912"
          src="/external/rectangle243912-ul66-200h.png"
          className="loginscreen-rectangle24"
        />
        <div className="loginscreen-byerafiki">
          <div className="loginscreen-backgroundcomplete">
            <img
              alt="Vector3912"
              src="/external/vector3912-buu.svg"
              className="loginscreen-vector10"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-juof.svg"
              className="loginscreen-vector11"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-0lcyb.svg"
              className="loginscreen-vector12"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-gzba.svg"
              className="loginscreen-vector13"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-fsq.svg"
              className="loginscreen-vector14"
            />
          </div>
          <div className="loginscreen-shadow">
            <img
              alt="path3912"
              src="/external/path3912-dysi.svg"
              className="loginscreen-path"
            />
          </div>
          <div className="loginscreen-character1">
            <img
              alt="Vector3912"
              src="/external/vector3912-qdfv.svg"
              className="loginscreen-vector15"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-0h5r.svg"
              className="loginscreen-vector16"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-rfuk.svg"
              className="loginscreen-vector17"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-ufy.svg"
              className="loginscreen-vector18"
            />
            <img
              alt="Vector3912"
              src="/external/vector3912-06og.svg"
              className="loginscreen-vector19"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-lfw8.svg"
              className="loginscreen-vector20"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-jbta.svg"
              className="loginscreen-vector21"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-sin9.svg"
              className="loginscreen-vector22"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-hibo.svg"
              className="loginscreen-vector23"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-rzjn.svg"
              className="loginscreen-vector24"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-xhz.svg"
              className="loginscreen-vector25"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-9xa.svg"
              className="loginscreen-vector26"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-ogx.svg"
              className="loginscreen-vector27"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-k99.svg"
              className="loginscreen-vector28"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-1cp.svg"
              className="loginscreen-vector29"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-bs3a.svg"
              className="loginscreen-vector30"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-qvh8.svg"
              className="loginscreen-vector31"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-ud7a.svg"
              className="loginscreen-vector32"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-841g.svg"
              className="loginscreen-vector33"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-7w1.svg"
              className="loginscreen-vector34"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-jsqn.svg"
              className="loginscreen-vector35"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-rs7.svg"
              className="loginscreen-vector36"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-8c2d.svg"
              className="loginscreen-vector37"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-iago.svg"
              className="loginscreen-vector38"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-pb0or.svg"
              className="loginscreen-vector39"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-kjsk.svg"
              className="loginscreen-vector40"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-7wrx.svg"
              className="loginscreen-vector41"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-2j7k.svg"
              className="loginscreen-vector42"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-t3pj.svg"
              className="loginscreen-vector43"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-fz7.svg"
              className="loginscreen-vector44"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-5y1.svg"
              className="loginscreen-vector45"
            />
          </div>
          <div className="loginscreen-character2">
            <img
              alt="Vector3913"
              src="/external/vector3913-f9ff.svg"
              className="loginscreen-vector46"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-1ux8.svg"
              className="loginscreen-vector47"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-t0js.svg"
              className="loginscreen-vector48"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-l74t.svg"
              className="loginscreen-vector49"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-p7nt.svg"
              className="loginscreen-vector50"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-s6pe.svg"
              className="loginscreen-vector51"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-k8zo.svg"
              className="loginscreen-vector52"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-qej.svg"
              className="loginscreen-vector53"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-me7.svg"
              className="loginscreen-vector54"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-afxj6.svg"
              className="loginscreen-vector55"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-ve6i.svg"
              className="loginscreen-vector56"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-i5o8.svg"
              className="loginscreen-vector57"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-e2en.svg"
              className="loginscreen-vector58"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-npk.svg"
              className="loginscreen-vector59"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-bsbv.svg"
              className="loginscreen-vector60"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-80rm.svg"
              className="loginscreen-vector61"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-e8n7.svg"
              className="loginscreen-vector62"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-jv5o.svg"
              className="loginscreen-vector63"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-31bi.svg"
              className="loginscreen-vector64"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-nk2f.svg"
              className="loginscreen-vector65"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-yc2.svg"
              className="loginscreen-vector66"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-d9ki.svg"
              className="loginscreen-vector67"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-uo54.svg"
              className="loginscreen-vector68"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-r76p.svg"
              className="loginscreen-vector69"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-4yc.svg"
              className="loginscreen-vector70"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-153d.svg"
              className="loginscreen-vector71"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-fog9.svg"
              className="loginscreen-vector72"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-nak.svg"
              className="loginscreen-vector73"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-0gnq.svg"
              className="loginscreen-vector74"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-odko.svg"
              className="loginscreen-vector75"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-k4fk.svg"
              className="loginscreen-vector76"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-yua.svg"
              className="loginscreen-vector77"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-6wph.svg"
              className="loginscreen-vector78"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-g6oy.svg"
              className="loginscreen-vector79"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-jgvje.svg"
              className="loginscreen-vector80"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-zu3o.svg"
              className="loginscreen-vector81"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-g3pi.svg"
              className="loginscreen-vector82"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-sm0q.svg"
              className="loginscreen-vector83"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-iyx5.svg"
              className="loginscreen-vector84"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-ya9g3.svg"
              className="loginscreen-vector85"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-avk.svg"
              className="loginscreen-vector86"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-cck9.svg"
              className="loginscreen-vector87"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-2kih.svg"
              className="loginscreen-vector88"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-ul98.svg"
              className="loginscreen-vector89"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-5e7k.svg"
              className="loginscreen-vector90"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-068.svg"
              className="loginscreen-vector91"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-nofa.svg"
              className="loginscreen-vector92"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-15oe.svg"
              className="loginscreen-vector93"
            />
            <img
              alt="Vector3913"
              src="/external/vector3913-yj9d.svg"
              className="loginscreen-vector94"
            />
          </div>
        </div>
        <div className="loginscreen-icon">
          <span className="loginscreen-text3"></span>
        </div>
      </div>
    </div>
  )
}

export default Loginscreen
