import React from 'react'

import { Helmet } from 'react-helmet'

import './loginscreen2.css'

const Loginscreen2 = (props) => {
  return (
    <div className="loginscreen2-container">
      <Helmet>
        <title>exported project</title>
      </Helmet>
      <div className="loginscreen2-loginscreen">
        <div className="loginscreen2-status-bari-phone13">
          <div className="loginscreen2-left-side">
            <div className="loginscreen2-frame-status-bartime">
              <span className="loginscreen2-text10 DefaultBoldBody">
                <span>9:41</span>
              </span>
            </div>
          </div>
          <div className="loginscreen2-right-side">
            <div className="loginscreen2-battery">
              <img
                alt="OutlineI125"
                src="/external/outlinei125-42f.svg"
                className="loginscreen2-outline"
              />
              <img
                alt="BatteryEndI125"
                src="/external/batteryendi125-414.svg"
                className="loginscreen2-battery-end"
              />
              <img
                alt="FillI125"
                src="/external/filli125-nram.svg"
                className="loginscreen2-fill"
              />
            </div>
            <img
              alt="WifiI125"
              src="/external/wifii125-htq7.svg"
              className="loginscreen2-wifi"
            />
            <img
              alt="IconMobileSignalI125"
              src="/external/iconmobilesignali125-hji.svg"
              className="loginscreen2-icon-mobile-signal"
            />
          </div>
        </div>
        <img
          alt="Rectangle241259"
          src="/external/rectangle241259-gm25-200h.png"
          className="loginscreen2-rectangle24"
        />
        <div className="loginscreen2-byerafiki">
          <div className="loginscreen2-backgroundcomplete">
            <img
              alt="Vector1260"
              src="/external/vector1260-2wzd.svg"
              className="loginscreen2-vector10"
            />
            <img
              alt="Vector1260"
              src="/external/vector1260-m5i6.svg"
              className="loginscreen2-vector11"
            />
            <img
              alt="Vector1260"
              src="/external/vector1260-c1m.svg"
              className="loginscreen2-vector12"
            />
            <img
              alt="Vector1260"
              src="/external/vector1260-wfwe.svg"
              className="loginscreen2-vector13"
            />
            <img
              alt="Vector1260"
              src="/external/vector1260-xt6.svg"
              className="loginscreen2-vector14"
            />
            <img
              alt="Vector1260"
              src="/external/vector1260-e14.svg"
              className="loginscreen2-vector15"
            />
            <img
              alt="Vector1260"
              src="/external/vector1260-uij4.svg"
              className="loginscreen2-vector16"
            />
          </div>
          <div className="loginscreen2-shadow">
            <img
              alt="path1261"
              src="/external/path1261-b713.svg"
              className="loginscreen2-path"
            />
          </div>
          <div className="loginscreen2-character1">
            <img
              alt="Vector1261"
              src="/external/vector1261-cfaq.svg"
              className="loginscreen2-vector17"
            />
            <img
              alt="Vector1261"
              src="/external/vector1261-avgp.svg"
              className="loginscreen2-vector18"
            />
            <img
              alt="Vector1261"
              src="/external/vector1261-s1si.svg"
              className="loginscreen2-vector19"
            />
            <img
              alt="Vector1261"
              src="/external/vector1261-ef9.svg"
              className="loginscreen2-vector20"
            />
            <img
              alt="Vector1261"
              src="/external/vector1261-cmiq.svg"
              className="loginscreen2-vector21"
            />
            <img
              alt="Vector1261"
              src="/external/vector1261-1i5h.svg"
              className="loginscreen2-vector22"
            />
            <img
              alt="Vector1261"
              src="/external/vector1261-m36.svg"
              className="loginscreen2-vector23"
            />
            <img
              alt="Vector1261"
              src="/external/vector1261-mu1r.svg"
              className="loginscreen2-vector24"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-icx.svg"
              className="loginscreen2-vector25"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-uwlo.svg"
              className="loginscreen2-vector26"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-9zk.svg"
              className="loginscreen2-vector27"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-7yag.svg"
              className="loginscreen2-vector28"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-9809.svg"
              className="loginscreen2-vector29"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-3iof.svg"
              className="loginscreen2-vector30"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-y3h7.svg"
              className="loginscreen2-vector31"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-8wc.svg"
              className="loginscreen2-vector32"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-4wmd.svg"
              className="loginscreen2-vector33"
            />
            <img
              alt="Vector1262"
              src="/external/vector1262-95wg.svg"
              className="loginscreen2-vector34"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-zf2.svg"
              className="loginscreen2-vector35"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-ofyg.svg"
              className="loginscreen2-vector36"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-40ub.svg"
              className="loginscreen2-vector37"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-l23i.svg"
              className="loginscreen2-vector38"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-d5x2.svg"
              className="loginscreen2-vector39"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-22ie.svg"
              className="loginscreen2-vector40"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-adxv.svg"
              className="loginscreen2-vector41"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-y7mo.svg"
              className="loginscreen2-vector42"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-q33.svg"
              className="loginscreen2-vector43"
            />
            <img
              alt="Vector1263"
              src="/external/vector1263-aczb.svg"
              className="loginscreen2-vector44"
            />
            <img
              alt="Vector1264"
              src="/external/vector1264-t7k.svg"
              className="loginscreen2-vector45"
            />
            <img
              alt="Vector1264"
              src="/external/vector1264-pkop.svg"
              className="loginscreen2-vector46"
            />
            <img
              alt="Vector1264"
              src="/external/vector1264-p3z.svg"
              className="loginscreen2-vector47"
            />
          </div>
          <div className="loginscreen2-character2">
            <img
              alt="Vector1264"
              src="/external/vector1264-y5ch.svg"
              className="loginscreen2-vector48"
            />
            <img
              alt="Vector1264"
              src="/external/vector1264-5pwc.svg"
              className="loginscreen2-vector49"
            />
            <img
              alt="Vector1264"
              src="/external/vector1264-yj9h.svg"
              className="loginscreen2-vector50"
            />
            <img
              alt="Vector1264"
              src="/external/vector1264-eevu.svg"
              className="loginscreen2-vector51"
            />
            <img
              alt="Vector1264"
              src="/external/vector1264-5a.svg"
              className="loginscreen2-vector52"
            />
            <img
              alt="Vector1264"
              src="/external/vector1264-q74.svg"
              className="loginscreen2-vector53"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-bit.svg"
              className="loginscreen2-vector54"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-wbx8.svg"
              className="loginscreen2-vector55"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-brkx.svg"
              className="loginscreen2-vector56"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-6oow.svg"
              className="loginscreen2-vector57"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-vkd.svg"
              className="loginscreen2-vector58"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-kmtd.svg"
              className="loginscreen2-vector59"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-b4q5.svg"
              className="loginscreen2-vector60"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-my8s.svg"
              className="loginscreen2-vector61"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-frz9.svg"
              className="loginscreen2-vector62"
            />
            <img
              alt="Vector1265"
              src="/external/vector1265-p32f.svg"
              className="loginscreen2-vector63"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-glcn.svg"
              className="loginscreen2-vector64"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-l7mn.svg"
              className="loginscreen2-vector65"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-s1q.svg"
              className="loginscreen2-vector66"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-6iz5.svg"
              className="loginscreen2-vector67"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-td4l.svg"
              className="loginscreen2-vector68"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-8r3.svg"
              className="loginscreen2-vector69"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-kfqb.svg"
              className="loginscreen2-vector70"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-cl1.svg"
              className="loginscreen2-vector71"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-8bes.svg"
              className="loginscreen2-vector72"
            />
            <img
              alt="Vector1266"
              src="/external/vector1266-8wvi.svg"
              className="loginscreen2-vector73"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-gy2.svg"
              className="loginscreen2-vector74"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-z1fi.svg"
              className="loginscreen2-vector75"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-o1v.svg"
              className="loginscreen2-vector76"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-q6sc.svg"
              className="loginscreen2-vector77"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-n5yk.svg"
              className="loginscreen2-vector78"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-74f.svg"
              className="loginscreen2-vector79"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-jzh.svg"
              className="loginscreen2-vector80"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-9uz.svg"
              className="loginscreen2-vector81"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-5a8p.svg"
              className="loginscreen2-vector82"
            />
            <img
              alt="Vector1267"
              src="/external/vector1267-6gtg.svg"
              className="loginscreen2-vector83"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-39l.svg"
              className="loginscreen2-vector84"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-tifb.svg"
              className="loginscreen2-vector85"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-h1km.svg"
              className="loginscreen2-vector86"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-2sj.svg"
              className="loginscreen2-vector87"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-dkhw.svg"
              className="loginscreen2-vector88"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-k28.svg"
              className="loginscreen2-vector89"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-lmfc.svg"
              className="loginscreen2-vector90"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-50l.svg"
              className="loginscreen2-vector91"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-pq.svg"
              className="loginscreen2-vector92"
            />
            <img
              alt="Vector1268"
              src="/external/vector1268-h4z.svg"
              className="loginscreen2-vector93"
            />
            <img
              alt="Vector1269"
              src="/external/vector1269-94ur.svg"
              className="loginscreen2-vector94"
            />
            <img
              alt="Vector1269"
              src="/external/vector1269-kaus.svg"
              className="loginscreen2-vector95"
            />
            <img
              alt="Vector1269"
              src="/external/vector1269-28je.svg"
              className="loginscreen2-vector96"
            />
          </div>
        </div>
        <div className="loginscreen2-icon1">
          <span className="loginscreen2-text12"></span>
        </div>
        <div className="loginscreen2-frame16">
          <div className="loginscreen2-text-styles1">
            <span className="loginscreen2-text13 Heading">
              <span>Login</span>
            </span>
          </div>
          <div className="loginscreen2-frame15">
            <div className="loginscreen2-frame12">
              <div className="loginscreen2-icon2">
                <span className="loginscreen2-text15 SingleLineBodyBase">
                  @
                </span>
              </div>
              <div className="loginscreen2-text-styles2">
                <span className="loginscreen2-text16 SingleLineBodyBase">
                  <span>Email</span>
                </span>
              </div>
            </div>
            <div className="loginscreen2-frame14">
              <div className="loginscreen2-icon3">
                <span className="loginscreen2-text18"></span>
              </div>
              <div className="loginscreen2-text-styles3">
                <span className="loginscreen2-text19 SingleLineBodyBase">
                  <span>Password</span>
                </span>
              </div>
            </div>
            <div className="loginscreen2-text-styles4">
              <span className="loginscreen2-text21 BodySmall">
                <span> Forgot Password?</span>
              </span>
            </div>
          </div>
        </div>
        <div className="loginscreen2-frame18">
          <button className="loginscreen2-buttons1">
            <span className="loginscreen2-text23 Body-14pxMedium">
              <span>Continue</span>
            </span>
          </button>
          <div className="loginscreen2-frame17">
            <img
              alt="Line131270"
              src="/external/line131270-8r9l.svg"
              className="loginscreen2-line13"
            />
            <div className="loginscreen2-text-styles5">
              <span className="loginscreen2-text25">
                <span>OR</span>
              </span>
            </div>
            <img
              alt="Line141271"
              src="/external/line141271-f50c.svg"
              className="loginscreen2-line14"
            />
          </div>
          <button className="loginscreen2-buttons2">
            <img
              alt="svg011271"
              src="/external/svg011271-l82i.svg"
              className="loginscreen2-svg01"
            />
            <span className="loginscreen2-text27 Body-14pxMedium">
              <span>Login with Google</span>
            </span>
          </button>
        </div>
      </div>
    </div>
  )
}

export default Loginscreen2
